let strip1 = neopixel.create(DigitalPin.P16, 4, NeoPixelMode.RGB)
strip1.clear()
strip1.rotate(1)
strip1.show()
basic.forever(function () {
    magicbit.Servo(magicbit.Servos.S2, -30)
    basic.pause(100)
    magicbit.Servospeed(magicbit.Servos.S1, 0, 90, 2)
    basic.pause(50)
    magicbit.Servospeed(magicbit.Servos.S4, -30, 90, 1)
    basic.pause(200)
    magicbit.Servospeed(magicbit.Servos.S2, -30, 90, 3)
})
