let strip1 = neopixel.create(DigitalPin.P16, 4, NeoPixelMode.RGB)
strip1.clear()
strip1.rotate(1)
strip1.show()
basic.forever(function () {
    strip1.show()
    basic.showNumber(0)
    basic.showNumber(1)
    basic.showNumber(2)
    basic.showNumber(3)
    strip1.clear()
    basic.showNumber(4)
    basic.showNumber(5)
})
